FROM python:3.9-slim

COPY . /app
WORKDIR /app

RUN pip install pip --upgrade
RUN pip install -r requirements.txt

RUN chmod +x run.sh
RUN chmod +x run-worker.sh


ENV USE_DOTENV_PKG=1

CMD ["./run.sh"]